"""Analyze the job-postings dataset and export insights as JSON for the frontend.

Run:  python3 analyze.py
Reads data/job_postings.csv, writes output/insights.json.
"""
import csv, json
from collections import Counter, defaultdict

with open("data/job_postings.csv") as f:
    rows = list(csv.DictReader(f))

def pct(n, total):
    return round(100 * n / total, 1)

total = len(rows)

# --- headline stats ---
salaries = [float(r["salary_lpa"]) for r in rows]
avg_salary = round(sum(salaries) / total, 1)
remote = sum(1 for r in rows if r["location"] == "Remote")

# --- postings per role ---
role_counts = Counter(r["title"] for r in rows)
roles = [{"role": k, "postings": v, "share_pct": pct(v, total)} for k, v in role_counts.most_common()]

# --- average salary per role ---
sal_by_role = defaultdict(list)
for r in rows:
    sal_by_role[r["title"]].append(float(r["salary_lpa"]))
salary_by_role = sorted(
    ({"role": k, "avg_salary_lpa": round(sum(v) / len(v), 1)} for k, v in sal_by_role.items()),
    key=lambda x: -x["avg_salary_lpa"])

# --- top skills ---
skill_counts = Counter()
for r in rows:
    for s in r["skills"].split(";"):
        skill_counts[s.strip()] += 1
top_skills = [{"skill": k, "postings": v} for k, v in skill_counts.most_common(15)]

# --- location distribution ---
loc_counts = Counter(r["location"] for r in rows)
locations = [{"location": k, "postings": v, "share_pct": pct(v, total)} for k, v in loc_counts.most_common()]

# --- postings per month ---
month_counts = Counter(r["posted_date"][:7] for r in rows)
trend = [{"month": m, "postings": month_counts[m]} for m in sorted(month_counts)]

# --- job type split ---
type_counts = Counter(r["job_type"] for r in rows)
job_types = [{"type": k, "postings": v} for k, v in type_counts.most_common()]

# --- skills most common for frontend roles (example of a sliced insight) ---
fe_skills = Counter()
for r in rows:
    if r["title"] == "Frontend Developer":
        for s in r["skills"].split(";"):
            fe_skills[s.strip()] += 1
frontend_skills = [{"skill": k, "postings": v} for k, v in fe_skills.most_common(8)]

insights = {
    "dataset": {"name": "job_postings.csv", "rows": total,
                "note": "Synthetic sample dataset generated by analysis/generate_data.py"},
    "headline": {
        "total_postings": total,
        "avg_salary_lpa": avg_salary,
        "remote_share_pct": pct(remote, total),
        "distinct_roles": len(role_counts),
    },
    "roles": roles,
    "salary_by_role": salary_by_role,
    "top_skills": top_skills,
    "locations": locations,
    "monthly_trend": trend,
    "job_types": job_types,
    "frontend_skills": frontend_skills,
}

with open("output/insights.json", "w") as f:
    json.dump(insights, f, indent=2)
print(f"Analyzed {total} rows -> output/insights.json")
print("Headline:", json.dumps(insights["headline"]))
